### ISSUE TITLE
Za dużo tych wyjątków

### ISSUE THREAD

**Issue by DevWojtekC** [KamilCiemiega/CRM#12]
https://github.com/KamilCiemiega/CRM/blob/ed30d31d3b00f07e7a886e9b2e285c978816f5b9/backend/src/main/java/com/crm/service/serviceImpl/MessageFolderServiceImpl.java#L76

Nie musisz wprowadzać osobno `NoSuch(Message|Folder|User)Exception`. Wystarczy jeden `NoSuchEntityException` albo `ElementNotFoundException`. Natomiast bałaganem jest rzucać `NoSuchMessageException` jak aktualizujesz folder

**Comment by KamilCiemiega** [comment]
Dodałem klasę:

@ResponseStatus(HttpStatus.NOT_FOUND)
public class NoSuchEntityException extends RuntimeException{
    public NoSuchEntityException(String message) { super(message);}
}
