### ISSUE TITLE
Co, jeżeli owner is null? To jest poprawny request? 

### ISSUE THREAD

**Issue by DevWojtekC** [KamilCiemiega/CRM#13]
https://github.com/KamilCiemiega/CRM/blob/ed30d31d3b00f07e7a886e9b2e285c978816f5b9/backend/src/main/java/com/crm/service/serviceImpl/MessageFolderServiceImpl.java#L88-L92

Ogólnie owner wygląda na obowiązkowe pole. W takiej sytuacji raczej:

1. Na początku metody zrób walidację, czy wszystkie dane wejściowe są poprawne. 
2. Dopiero wtedy zacznij wprowadzać zmiany w bazie

**Comment by KamilCiemiega** [comment]
Poprawiona metoda: 

    @Override
    @Transactional
    public MessageFolderDTO save(MessageFolderDTO messageFolderDTO) {
        if (messageFolderDTO.getName() == null || messageFolderDTO.getName().trim().isEmpty()) {
            throw new IllegalArgumentException("Folder name cannot be null or empty.");
        }

        if (messageFolderDTO.getOwnerUserId() == null) {
            throw new IllegalArgumentException("Owner user ID must be provided.");
        }

        if (messageFolderDTO.getParentFolderId() != null && messageFolderDTO.getParentFolderId() <= 0) {
            throw new IllegalArgumentException("Parent folder ID must be greater than 0.");
        }

        MessageFolder newMessageFolder = modelMapper.map(messageFolderDTO, MessageFolder.class);

        if (messageFolderDTO.getParentFolderId() != null) {
            MessageFolder parentFolder = messageFolderRepository.findById(messageFolderDTO.getParentFolderId())
                    .orElseThrow(() -> new NoSuchEntityException("Parent folder not found for ID: " + messageFolderDTO.getParentFolderId()));
            newMessageFolder.setParentFolder(parentFolder);
        }

        User user = userRepository.findById(messageFolderDTO.getOwnerUserId())
                .orElseThrow(() -> new NoSuchEntityException("User not found for ID: " + messageFolderDTO.getOwnerUserId()));
        newMessageFolder.setUser(user);

        MessageFolder savedFolder = messageFolderRepository.save(newMessageFolder);

        return modelMapper.map(savedFolder, MessageFolderDTO.class);
    }
